# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build for macOS

on:
  push:
    branches:
      - master
#  release:
#    types:
#      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'
    - name: Get Latest Release
      id: release
      uses: InsonusK/get-latest-release@v1.1.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        view_top: 1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-macos-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-macos-
    - name: Import Certs
      uses: apple-actions/import-codesign-certs@v2
      id: importcerts
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        keychain-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
#    - name: Build with Gradle
#      run: |
#        ./gradlew packageDmg \
#            -Pcompose.desktop.mac.sign=true \
#            -Pcompose.desktop.mac.signing.identity="${{ secrets.MACOS_SIGNING_ID }}"
#        ./gradlew --stop
    - name: Build, Sign, and Notarize with Gradle
      run: |
        ./gradlew notarizeReleaseDmg \
            -Pcompose.desktop.mac.notarization.appleID="${{ secrets.MACOS_NOTARIZATION_ID }}" \
            -Pcompose.desktop.mac.notarization.password="${{ secrets.MACOS_NOTARIZATION_PASSWORD }}" \
            -Pcompose.desktop.mac.notarization.teamID="${{ secrets.MACOS_TEAM_ID }}" \
            -Pcompose.desktop.mac.sign=true \
            -Pcompose.desktop.mac.signing.identity="${{ secrets.MACOS_SIGNING_ID }}"
        ./gradlew --stop
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${{ github.workspace }}/desktop/build/compose/logs/
    - name: Check Output Exists
      run: ls -laR ${{ github.workspace }}/desktop/build/compose/binaries/main-release/dmg/
    - name: Create Release ZIP
      uses: papeloto/action-zip@v1
      with:
        dest: 'Bifrost_macOS.zip'
        files: desktop/build/compose/binaries/main-release/dmg/
    - name: Upload DMG
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Bifrost
        path: ${{ github.workspace }}/desktop/build/compose/binaries/main-release/dmg/Bifrost-*.dmg
    - name: Upload Release ZIP
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'Bifrost_macOS.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: false
        omitBodyDuringUpdate: true
        tag: ${{ steps.release.outputs.tag_name }}
